//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangSite.Entities.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Mobi { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Content { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
    }
}
