//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToanThangSite.Entities.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int SliderID { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Description { get; set; }
    }
}
